# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

lite3:
  dt: 0.005
  decimation: 4
  fixed_kp: [60.0, 60.0, 60.0,
             60.0, 60.0, 60.0,
             60.0, 60.0, 60.0,
             60.0, 60.0, 60.0]
  fixed_kd: [1.0, 1.0, 1.0,
             1.0, 1.0, 1.0,
             1.0, 1.0, 1.0,
             1.0, 1.0, 1.0]
  num_of_dofs: 12
  wheel_indices: []
  torque_limits: [30.0, 30.0, 30.0,
                  30.0, 30.0, 30.0,
                  30.0, 30.0, 30.0,
                  30.0, 30.0, 30.0]
  default_dof_pos: [ 0.0, -0.80, 1.50,
                     0.0, -0.80, 1.50,
                     0.0, -0.80, 1.50,
                     0.0, -0.80, 1.50]
  joint_names: ["FL_HipX", "FL_HipY", "FL_Knee",
                "HL_HipX", "HL_HipY", "HL_Knee",
                "FR_HipX", "FR_HipY", "FR_Knee",
                "HR_HipX", "HR_HipY", "HR_Knee"]
  joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller",
                           "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller"]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]