# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

g1/robot_lab:
  model_name: "policy.pt"
  framework: "isaacsim"
  dt: 0.005
  decimation: 4
  num_observations: 81
  observations: ["ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions", "phase"]
  observations_history: []  # 0 is the latest observation
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0]
  rl_kp: [200.0, 150.0, 150.0, 200.0, 20.0, 20.0,
          200.0, 150.0, 150.0, 200.0, 20.0, 20.0,
          200.0,
          40.0, 40.0, 40.0, 40.0, 40.0,
          40.0, 40.0, 40.0, 40.0, 40.0]
  rl_kd: [5.0, 5.0, 5.0, 5.0, 2.0, 2.0,
          5.0, 5.0, 5.0, 5.0, 2.0, 2.0,
          5.0,
          10.0, 10.0, 10.0, 10.0, 10.0,
          10.0, 10.0, 10.0, 10.0, 10.0]
  fixed_kp: [200.0, 150.0, 150.0, 200.0, 20.0, 20.0,
             200.0, 150.0, 150.0, 200.0, 20.0, 20.0,
             20.0,
             40.0, 40.0, 40.0, 40.0, 40.0,
             40.0, 40.0, 40.0, 40.0, 40.0]
  fixed_kd: [5.0, 5.0, 5.0, 5.0, 2.0, 2.0,
             5.0, 5.0, 5.0, 5.0, 2.0, 2.0,
             5.0,
             1.0, 1.0, 1.0, 1.0, 1.0,
             1.0, 1.0, 1.0, 1.0, 1.0]
  num_of_dofs: 23
  action_scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [300.0, 300.0, 300.0, 300.0, 20.0, 20.0,
                  300.0, 300.0, 300.0, 300.0, 20.0, 20.0,
                  300.0,
                  300.0, 300.0, 300.0, 300.0, 300.0,
                  300.0, 300.0, 300.0, 300.0, 300.0]
  default_dof_pos: [-0.2, 0.0, 0.0, 0.42, -0.23, 0.0,
                    -0.2, 0.0, 0.0, 0.42, -0.23, 0.0,
                    0.0,
                    0.35, 0.16, 0.0, 0.87, 0.0,
                    0.35, -0.16, 0.0, 0.87, 0.0]
  joint_controller_names: [left_hip_pitch_controller, left_hip_roll_controller, left_hip_yaw_controller, left_knee_controller, left_ankle_pitch_controller, left_ankle_roll_controller,
                           right_hip_pitch_controller, right_hip_roll_controller, right_hip_yaw_controller, right_knee_controller, right_ankle_pitch_controller, right_ankle_roll_controller,
                           waist_yaw_controller,
                           left_shoulder_pitch_controller, left_shoulder_roll_controller, left_shoulder_yaw_controller, left_elbow_controller, left_wrist_roll_controller,
                           right_shoulder_pitch_controller, right_shoulder_roll_controller, right_shoulder_yaw_controller, right_elbow_controller, right_wrist_roll_controller]
  command_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
  state_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
