controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz
        # use_sim_time: true  # If running in simulation

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        imu_sensor_broadcaster:
            type: imu_sensor_broadcaster/ImuSensorBroadcaster

        robot_joint_controller:
            type: robot_joint_controller/RobotJointControllerGroup

robot_joint_controller:
    ros__parameters:
        joints:
            - FL_hip_joint
            - FL_thigh_joint
            - FL_calf_joint
            - FR_hip_joint
            - FR_thigh_joint
            - FR_calf_joint
            - RL_hip_joint
            - RL_thigh_joint
            - RL_calf_joint
            - RR_hip_joint
            - RR_thigh_joint
            - RR_calf_joint

imu_sensor_broadcaster:
    ros__parameters:
        sensor_name: "imu_sensor"
        frame_id: imu_link