# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

g1/robomimic/loco:
  model_name: "policy_29dof.pt"
  num_observations: 96
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: []  # 0 is the latest observation
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0        , -100.0, -100.0,
                       -100.0, -100.0        , -100.0, -100.0,
                       -100.0, -100.0        , -100.0, -100.0,
                                               -100.0, -100.0,
                                               -100.0, -100.0,
                                               -100.0, -100.0,
                                               -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0        , 100.0, 100.0,
                       100.0, 100.0        , 100.0, 100.0,
                       100.0, 100.0        , 100.0, 100.0,
                                             100.0, 100.0,
                                             100.0, 100.0,
                                             100.0, 100.0,
                                             100.0, 100.0]
  rl_kp: [200.0, 200.0, 200.0,
          150.0, 150.0, 200.0,
          150.0, 150.0, 200.0,
          200.0, 200.0       , 100.0, 100.0,
           20.0,  20.0       , 100.0, 100.0,
           20.0,  20.0       ,  50.0,  50.0,
                                50.0,  50.0,
                                40.0,  40.0,
                                40.0,  40.0,
                                40.0,  40.0]
  rl_kd: [5.0, 5.0, 5.0,
          5.0, 5.0, 5.0,
          5.0, 5.0, 5.0,
          5.0, 5.0     , 2.0, 2.0,
          2.0, 2.0     , 2.0, 2.0,
          2.0, 2.0     , 2.0, 2.0,
                         2.0, 2.0,
                         2.0, 2.0,
                         2.0, 2.0,
                         2.0, 2.0]
  fixed_kp: [100.0, 150.0, 300.0,
             100.0, 100.0, 300.0,
             100.0, 100.0, 300.0,
             150.0, 150.0       , 100.0, 100.0,
              40.0,  40.0       , 100.0, 100.0,
              40.0,  40.0       ,  50.0,  50.0,
                                   50.0,  50.0,
                                   20.0,  20.0,
                                   20.0,  20.0,
                                   20.0,  20.0]
  fixed_kd: [2.0, 2.0, 3.0,
             2.0, 2.0, 3.0,
             2.0, 2.0, 3.0,
             4.0, 4.0     , 2.0, 2.0,
             2.0, 2.0     , 2.0, 2.0,
             2.0, 2.0     , 2.0, 2.0,
                            2.0, 2.0,
                            1.0, 1.0,
                            1.0, 1.0,
                            1.0, 1.0]
  num_of_dofs: 29
  action_scale: [0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25      , 0.25, 0.25,
                 0.25, 0.25      , 0.25, 0.25,
                 0.25, 0.25      , 0.25, 0.25,
                                   0.25, 0.25,
                                   0.25, 0.25,
                                   0.25, 0.25,
                                   0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 1.0
  ang_vel_scale: 1.0
  dof_pos_scale: 1.0
  dof_vel_scale: 1.0
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [ 88.0,  88.0, 88.0,
                   88.0,  88.0, 88.0,
                   88.0,  88.0, 88.0,
                  139.0, 139.0      , 25.0, 25.0,
                   50.0,  50.0      , 25.0, 25.0,
                   50.0,  50.0      , 25.0, 25.0,
                                      25.0, 25.0,
                                       5.0,  5.0,
                                       5.0,  5.0,
                                       5.0,  5.0]
  default_dof_pos: [-0.20, -0.20,  0.0,
                     0.00,  0.00,  0.0,
                     0.00,  0.00,  0.0,
                     0.42,  0.42      , 0.35,  0.35,
                    -0.23, -0.23      , 0.18, -0.18,
                     0.00,  0.00      , 0.00,  0.00,
                                        0.87,  0.87,
                                        0.00,  0.00,
                                        0.00,  0.00,
                                        0.00,  0.00]
  joint_names: [left_hip_pitch_joint, left_hip_roll_joint, left_hip_yaw_joint,
                left_knee_joint, left_ankle_pitch_joint, left_ankle_roll_joint,
                right_hip_pitch_joint, right_hip_roll_joint, right_hip_yaw_joint,
                right_knee_joint, right_ankle_pitch_joint                       , right_ankle_roll_joint, waist_yaw_joint,
                waist_roll_joint, waist_pitch_joint                             , left_shoulder_pitch_joint, left_shoulder_roll_joint,
                left_shoulder_yaw_joint, left_elbow_joint                       , left_wrist_roll_joint, left_wrist_pitch_joint,
                                                                                  left_wrist_yaw_joint, right_shoulder_pitch_joint,
                                                                                  right_shoulder_roll_joint, right_shoulder_yaw_joint,
                                                                                  right_elbow_joint, right_wrist_roll_joint,
                                                                                  right_wrist_pitch_joint, right_wrist_yaw_joint]
  joint_controller_names: [left_hip_pitch_controller, left_hip_roll_controller, left_hip_yaw_controller,
                           left_knee_controller, left_ankle_pitch_controller, left_ankle_roll_controller,
                           right_hip_pitch_controller, right_hip_roll_controller, right_hip_yaw_controller,
                           right_knee_controller, right_ankle_pitch_controller                            , right_ankle_roll_controller, waist_yaw_controller,
                           waist_roll_controller, waist_pitch_controller                                  , left_shoulder_pitch_controller, left_shoulder_roll_controller,
                           left_shoulder_yaw_controller, left_elbow_controller                            , left_wrist_roll_controller, left_wrist_pitch_controller,
                                                                                                            left_wrist_yaw_controller, right_shoulder_pitch_controller,
                                                                                                            right_shoulder_roll_controller, right_shoulder_yaw_controller,
                                                                                                            right_elbow_controller, right_wrist_roll_controller,
                                                                                                            right_wrist_pitch_controller, right_wrist_yaw_controller]
  joint_mapping: [0, 6, 12,
                  1, 7, 13,
                  2, 8, 14,
                  3, 9    , 15, 22,
                  4, 10   , 16, 23,
                  5, 11   , 17, 24,
                            18, 25,
                            19, 26,
                            20, 27,
                            21, 28]
