openloong_gazebo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000  

    # left leg Controllers ---------------------------------------
    l_hip_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: l_hip_roll
        pid: {p: 57.0, i: 0.0, d: 5.7}
    
    l_hip_yaw_controller:
        type: robot_joint_controller/RobotJointController
        joint: l_hip_yaw
        pid: {p: 43.0, i: 0.0, d: 4.3}

    l_hip_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: l_hip_pitch
        pid: {p: 114.0, i: 0.0, d: 11.4}

    l_knee_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: l_knee_pitch
        pid: {p: 114.0, i: 0.0, d: 11.4}

    l_ankle_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: l_ankle_pitch
        pid: {p: 15.3, i: 0.0, d: 1.5}

    l_ankle_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: l_ankle_roll
        pid: {p: 15.3, i: 0.0, d: 1.5}


    # right leg Controllers ---------------------------------------
    r_hip_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: r_hip_roll
        pid: {p: 57.0, i: 0.0, d: 5.7}
    
    r_hip_yaw_controller:
        type: robot_joint_controller/RobotJointController
        joint: r_hip_yaw
        pid: {p: 43.0, i: 0.0, d: 4.3}

    r_hip_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: r_hip_pitch
        pid: {p: 114.0, i: 0.0, d: 11.4}

    r_knee_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: r_knee_pitch
        pid: {p: 114.0, i: 0.0, d: 11.4}

    r_ankle_pitch_controller:
        type: robot_joint_controller/RobotJointController
        joint: r_ankle_pitch
        pid: {p: 15.3, i: 0.0, d: 1.5}

    r_ankle_roll_controller:
        type: robot_joint_controller/RobotJointController
        joint: r_ankle_roll
        pid: {p: 15.3, i: 0.0, d: 1.5}

