# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

lite3:
  dt: 0.005
  decimation: 4
  fixed_kp: [60.0, 60.0, 60.0,
             60.0, 60.0, 60.0,
             60.0, 60.0, 60.0,
             60.0, 60.0, 60.0]
  fixed_kd: [1.0, 1.0, 1.0,
             1.0, 1.0, 1.0,
             1.0, 1.0, 1.0,
             1.0, 1.0, 1.0]
  num_of_dofs: 12
  wheel_indices: []
  torque_limits: [30.0, 30.0, 30.0,
                  30.0, 30.0, 30.0,
                  30.0, 30.0, 30.0,
                  30.0, 30.0, 30.0]
  default_dof_pos: [ 0.0, -0.80, 1.50,
                     0.0, -0.80, 1.50,
                     0.0, -0.80, 1.50,
                     0.0, -0.80, 1.50]
  joint_names: ["FL_HipX_joint", "FL_HipY_joint", "FL_Knee_joint",
                "FR_HipX_joint", "FR_HipY_joint", "FR_Knee_joint",
                "HL_HipX_joint", "HL_HipY_joint", "HL_Knee_joint",
                "HR_HipX_joint", "HR_HipY_joint", "HR_Knee_joint"]
  joint_controller_names: ["FL_HipX_controller", "FL_HipY_controller", "FL_Knee_controller",
                           "FR_HipX_controller", "FR_HipY_controller", "FR_Knee_controller",
                           "HL_HipX_controller", "HL_HipY_controller", "HL_Knee_controller",
                           "HR_HipX_controller", "HR_HipY_controller", "HR_Knee_controller"]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
