# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

lite3/himloco:
  model_name: "policy_6_11.pt"
  num_observations: 45
  observations: ["commands", "ang_vel_world", "gravity_vec", "dof_pos", "dof_vel", "actions"]
  observations_history: [0, 1, 2, 3, 4, 5]  # 0 is the latest observation
#   observations_history: [5, 4, 3, 2, 1, 0]  # 0 is the latest observation
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100]
  clip_actions_upper: [100, 100, 100,
                       100, 100, 100,
                       100, 100, 100,
                       100, 100, 100]
  rl_kp: [40, 40, 40,
          40, 40, 40,
          40, 40, 40,
          40, 40, 40]
  rl_kd: [1, 1, 1,
          1, 1, 1,
          1, 1, 1,
          1, 1, 1]
  fixed_kp: [40, 40, 40,
             40, 40, 40,
             40, 40, 40,
             40, 40, 40]
  fixed_kd: [1, 1, 1,
             1, 1, 1,
             1, 1, 1,
             1, 1, 1]
  num_of_dofs: 12
  action_scale: [0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25]
#   action_scale: [0.125, 0.25, 0.25,
#                  0.125, 0.25, 0.25,
#                  0.125, 0.25, 0.25,
#                  0.125, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  torque_limits: [33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5]
  default_dof_pos: [-0.1000, -0.8000, 1.5000,
                    0.1000, -0.8000, 1.5000,
                    -0.1000, -0.8000, 1.5000,
                    0.1000, -0.8000, 1.5000]
  joint_names: ["FL_HipX", "FL_HipY", "FL_Knee",
                "FR_HipX", "FR_HipY", "FR_Knee",
                "HL_HipX", "HL_HipY", "HL_Knee",
                "HR_HipX", "HR_HipY", "HR_Knee"]
  joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller"]
  joint_mapping: [0, 1, 2, 6, 7, 8, 3, 4, 5, 9, 10, 11]