# Copyright (c) 2024-2025 Ziqi Fan; Qingwei Ben
# SPDX-License-Identifier: Apache-2.0

g1/unitree_rl_gym:
  model_name: "motion.onnx"
  num_observations: 223
  observations: ["command_hussar", "ang_vel_hussar", "gravity_vec_multi_hussar", "dof_pos_multi_hussar", "dof_vel_multi_hussar", "prev_actions_multi_hussar", "grid_map_hussar"]
  observations_history: []  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  key_observations_history: [1, 1, 3, 3, 3, 3]
  key_observations_history_priority: "recent_first"
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
  rl_kp: [100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
          100.0, 100.0, 100.0, 150.0, 40.0, 40.0]
  rl_kd: [2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
          2.0, 2.0, 2.0, 4.0, 2.0, 2.0]
  fixed_kp: [100.0, 100.0, 100.0, 150.0, 40.0, 40.0,
             100.0, 100.0, 100.0, 150.0, 40.0, 40.0]
  fixed_kd: [2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
             2.0, 2.0, 2.0, 4.0, 2.0, 2.0]
  num_of_dofs: 23
  action_scale: [0.5, 0.5, 0.5, 0.5, 0.25, 0.25, 
                0.5, 0.5, 0.5, 0.5, 0.25, 0.25,
                0.25, 0.25, 0.25, 
                0.25, 0.25, 0.25, 0.25, 
                0.25, 0.25, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  torque_limits: [300.0, 300.0, 300.0, 300.0, 20.0, 20.0,
                  300.0, 300.0, 300.0, 300.0, 20.0, 20.0,
                  300.0, 300.0, 300.0,
                  300.0, 300.0, 300.0, 300.0,
                  300.0, 300.0, 300.0, 300.0
                  ]
  default_dof_pos: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                    -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]