<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find l4w4_description)/xacro/transmission.xacro"/>

    <xacro:macro name="leg" params="name mirror mirror_dae front_hind front_hind_dae *origin">

        <joint name="${name}_hip_joint" type="revolute">
            <xacro:insert_block name="origin"/>
            <parent link="trunk"/>
            <child link="${name}_hip"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="130" velocity="11.5" lower="-0.785" upper="0.785"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="130" velocity="11.5" lower="-0.785" upper="0.785"/>
            </xacro:if>            
        </joint>

        <link name="${name}_hip">
            <visual>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="-0.004726 -0.001176 0.000044"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0.004726 -0.001176 0.000044"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                    <origin rpy="0 0 0" xyz="-0.004726 0.001176 0.000044"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                    <origin rpy="0 0 0" xyz="0.004726 0.001176 0.000044"/>
                </xacro:if>
                <geometry>
                    <mesh filename="package://l4w4_description/meshes/shoulder_R.STL" scale="1 1 1"/>
                </geometry>
                <material name="orange"/>
            </visual>
            <collision>
                <origin rpy="${PI/2.0} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${hip_length}" radius="${hip_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${hip_com_x*front_hind} ${hip_com_y*mirror} ${hip_com_z}"/>
                <mass value="${hip_mass}"/>
                <inertia
                    ixx="${hip_ixx}" ixy="${hip_ixy*mirror*front_hind}" ixz="${hip_ixz*front_hind}"
                    iyy="${hip_iyy}" iyz="${hip_iyz*mirror}"
                    izz="${hip_izz}"/>       
            </inertial>
        </link>

        <joint name="${name}_thigh_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="${name}_hip"/>
            <child link="${name}_thigh"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit lower="-1.4" upper="3.14" effort="135" velocity="12.56"/>
        </joint>


        <link name="${name}_thigh">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <xacro:if value="${mirror_dae == True}">
                        <mesh filename="package://l4w4_description/meshes/thigh_R.STL" scale = "1 -1 1"/>
                    </xacro:if>
                    <xacro:if value="${mirror_dae == False}">
                        <mesh filename="package://l4w4_description/meshes/thigh_R.STL" scale="1 1 1"/>
                    </xacro:if>
                </geometry>
                <material name="orange"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 -0.1145 -0.100"/>
                <geometry>
                    <box size="0.122 0.044 0.32"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${thigh_com_x} ${thigh_com_y*mirror} ${thigh_com_z}"/>
                <mass value="${thigh_mass}"/>
                <inertia
                    ixx="${thigh_ixx}" ixy="${thigh_ixy*mirror}" ixz="${thigh_ixz}"
                    iyy="${thigh_iyy}" iyz="${thigh_iyz*mirror}"
                    izz="${thigh_izz}"/>       
            </inertial>
        </link>

        <joint name="${name}_calf_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 ${0.1145*mirror} -0.3"/>
            <parent link="${name}_thigh"/>
            <child link="${name}_calf"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit lower="-2.7" upper="-0.17" effort="135" velocity="12.56"/>
        </joint>

        <link name="${name}_calf">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <xacro:if value="${mirror_dae == True}">
                        <mesh filename="package://l4w4_description/meshes/shank_R.STL" scale = "1 -1 1"/>
                    </xacro:if>
                    <xacro:if value="${mirror_dae == False}">
                        <mesh filename="package://l4w4_description/meshes/shank_R.STL" scale="1 1 1"/>
                    </xacro:if>
                </geometry>
                <material name="orange"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 -0.2"/>
                <geometry>
                    <box size="0.06 0.03 0.1"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${calf_com_x} ${calf_com_y} ${calf_com_z}"/>
                <mass value="${calf_mass}"/>
                <inertia
                    ixx="${calf_ixx}" ixy="${calf_ixy}" ixz="${calf_ixz}"
                    iyy="${calf_iyy}" iyz="${calf_iyz}"
                    izz="${calf_izz}"/>       
            </inertial>
        </link>

        <joint name="${name}_foot_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 -0.3"/>
            <parent link="${name}_calf"/>
            <child link="${name}_foot"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit lower="-1000000" upper="1000000" effort="32" velocity="12.0"/>
        </joint>

        <link name="${name}_foot">
            <visual>
                <origin rpy="0 0 0" xyz="0 -0.0 0"/>
                <geometry>
                    <xacro:if value="${mirror_dae == True}">
                        <mesh filename="package://l4w4_description/meshes/wheel_R.STL" scale = "1 -1 1"/>
                    </xacro:if>
                    <xacro:if value="${mirror_dae == False}">
                        <mesh filename="package://l4w4_description/meshes/wheel_R.STL" scale="1 1 1"/>
                    </xacro:if>
                </geometry>
                <material name="orange"/>
            </visual>
            <collision>
                <origin rpy="1.570796327 0 0" xyz="0 -0.045 0"/>
                <geometry>
                    <cylinder length="0.038" radius="0.105"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${foot_com_x} ${foot_com_y} ${foot_com_z}"/>
                <mass value="${foot_mass}"/>
                <inertia
                    ixx="${foot_ixx}" ixy="${foot_ixy}" ixz="${foot_ixz}"
                    iyy="${foot_iyy}" iyz="${foot_iyz}"
                    izz="${foot_izz}"/>       
            </inertial>
        </link>
        

        <xacro:leg_transmission name="${name}"/>
    </xacro:macro>
</robot>
